config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope "/:locale", locale: /en|ka|ua/ do
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")

    get "/@:username/posts", to: "posts#user_posts", as: :user_posts
    get "/@:username/friends", to: "friends#user_friends", as: :user_friends
    get "/@:username", to: "posts#user_posts", as: :user_public_profile
    get "/posts/new", to: "posts#new_post", as: :create_new_post
    get "/post/:id/edit", to: "posts#edit_post", as: :edit_post
    patch "/post/:id", to: "posts#save_edit_post", as: :save_edit_post
    get "/@:username/post/:id", to: "posts#post", as: :show_post
    put "/posts/save", to: "posts#save_new_post", as: :save_new_post
    get "/post/:id/toggle_status", to: "posts#toggle_post_status", as: :toggle_post_status
    get "/profile/posts", to: "posts#user_posts_list", as: :user_posts_list
    get "/profile/settings", to: "users#settings", as: :user_settings
    get "/profile/settings/avatar", to: "users#avatar", as: :avatar
    get "/profile/settings/appearance", to: "users#appearance", as: :appearance
    post "/profile/appearance", to: "users#save_appearance", as: :save_appearance
    post "/profile/avatar", to: "users#save_avatar", as: :save_user_avatar
    get "/profile/settings/addresses", to: "addresses#address", as: :address
    get "/profile/settings/addresses/new", to: "addresses#new_address", as: :new_address
    post "/profile/addresses/new", to: "addresses#new_address", as: :find_address
    put "/profile/addresses/new", to: "addresses#new", as: :save_address    
    put "/post/:id/add_comment", to: "comments#save", as: :save_new_comment
    patch "/post/:id/comments/:comment_id/update", to: "comments#update", as: :save_edit_comment
    get "/user/activity", to: "users#activity", as: :user_profile_activity
    delete "/posts/:id/delete", to: "posts#delete_user_post", as: :delete_user_post
    get "/profile/settings/phones/new", to: "phones#new", as: :new_phone
    put "/profile/phones/new", to: "phones#save_new_phone", as: :save_phone   
    get "/profile/settings/phones", to: "phones#index", as: :phone
    delete "/profile/phone/:phone/delete", to: "phones#delete", as: :delete_phone
    get "/dm", to: "messages#index", as: :direct_messages
    get "/dm/@:username", to: "messages#user", as: :user_direct_messages

    get "/profile/settings/privacy", to: "privacy#index", as: :privacy
    put "/profile/settings/privacy", to: "privacy#save", as: :save_privacy
    get "/categories/new", to: "categories#new", as: :new_category
    put "/categories/new", to: "categories#create", as: :save_new_category
    get "/profile/categories", to: "categories#index", as: :user_post_actegories
    get "/category/:name", to: "categories#category_posts", as: :show_category_posts
    match '/search',  to: 'posts#search_posts', via: 'get', as: :search
    get "/charges/new", to: 'charges#new', as: :new_charge
    get "/premium", to: "users#premium", as: :premium
    post "/charges/new", to: 'charges#create_subscription', as: :charges
    match '/auth/:provider/callback', :to => 'omniauth#google_oauth2', :via => [:get, :post]

    post '/user/accept', to: 'requests#accept', as: :accept_friend
  end
  
  get '*all', to: 'application#error_page', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  resources :webhooks, only: [:create]
  put '/request/create', to: 'requests#create', as: :sent_friend_request
  delete '/request/destroy', to: 'requests#destroy', as: :destroy_friend_request
  post "/likes/save", to: "likes#save", as: :save_like
  # get '*unmatched_route', to: 'application#error_page'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, :counter_cache => true
  belongs_to :post, :counter_cache => true
  has_many :likes
  belongs_to :notification, optional: true
  belongs_to :parent,  class_name: "Comment", optional: true, counter_cache: :count_of_replies #-> requires "parent_id" column
  has_many   :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
 
  scope :is_parent, -> {
    where(:parent_id => nil)
  }
  scope :is_child, -> {
    where("parent_id IS NOT NULL")
  }

  validates :body, presence: true,  length: { minimum: 2, maximum: 555 }
  before_validation :strip_whitespace

  after_commit :notify_post_author, on: :create

  private
  
  def strip_whitespace
    self.body = self.body.strip unless self.body.nil?
  end

  def notify_post_author
    NewCommentNotifyPostAuthorJob.set(wait_until: Time.now + 1.minutes).perform_later self
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def save
    # @comment = current_user.comments.build(comment_params)
    @post = Post.find_by_hashid(params[:id])
    @comment = Comment.new(body: params['body'], user_id: current_user.id, post_id: @post.id, parent_id: params['parent_id'])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to show_post_url(@post.user.username, params[:id]), notice: "Comment was successfully created." }
        # format.json { render :show, status: :created, location: @blog }
      else
        format.html { redirect_to show_post_url(params[:id]), alert: "Comment was not created." }
        # format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find_by_hashid(params[:id])
    @comment = @post.comments.find_by(id: params[:comment_id], user_id: current_user.id)
    @comment.body = params[:body]

    respond_to do |format|
      if @comment.save
        format.html { redirect_back_or_to show_post_path(@post.user.username, @post.hashid), notice: "comment was successfully Edited." }
      else
        format.html { redirect_to show_post_path(@post.user.username, @post.hashid), alert: "Comment was not updated." }
      end
    end
  end


  private 

  def comment_params
    params.require(:comment).permit(:body, :comment_id, :parent_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
        
<div class="w-full dark:text-slate-300 dark:bg-zinc-800 my-2 mx-1 flex gap-3 rounded-lg -md bg-white p-2 text-black shadow-md border dark:border-gray-800">
  <!-- Content -->
  <div class = "w-full p-2">
    <!-- Header -->
    <div class="flex items-center justify-between py-1 pr-2">
      <!-- Author -->
      <div>
        <% if comment.user.avatar.attached? %>
          <%= image_tag comment.user.avatar.variant(:thumb), class: 'float-left w-8 h-8 rounded-lg -full mr-4 mb-2'%>
        <% else %>
          <%=image_tag("#{ENV['DEFAULT_AVATAR_IMAGE_PATH']}", :alt => "user photo", class: 'float-left mr-4 mb-2 w-8 h-8 rounded-lg -full') %>
        <% end %>
        <span class="font-bold text-gray-900 bg-white font-medium rounded-lg  text-sm px-5 py-2.5 text-center inline-flex items-center  dark:bg-zinc-800 dark:border-gray-700 dark:text-white mr-2 mb-2">
          <%=link_to h(comment.user.full_name) + ' ', user_posts_path(comment.user.username), class: "text-blue-400 hover:underline" %>
          <% if comment.user.premium? %>
            <svg data-tooltip-target="tooltip-light" data-tooltip-style="light" xmlns="http://www.w3.org/2000/svg" class="dark:text-orange-400 text-orange-300 h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
            </svg>
            <div id="tooltip-light" role="tooltip" class="inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium dark:text-slate-300 text-gray-900 bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-gray-500 shadow-sm opacity-0 tooltip">
              <%=t('premium user') %>
              <div class="tooltip-arrow" data-popper-arrow></div>
            </div>
          <% end %>
          <%=render 'layouts/post_date_section', post: comment%>
        </span>
      </div>
      <!-- Rate -->
    </div>
    <div x-data="{ open: false, word: 'Edit' }">
      <% if current_user.present?  && current_user.id == comment.user_id %>
        <button class="float-right -mt-12" x-on:click="open = ! open, word = (word == 'Edit') ? 'Cancel' : 'Edit'" x-text="word">Edit</button>
      <% end %>
      <div x-show="open">
        <%= form_with(url: save_edit_comment_path(comment.post, comment.id), html: { method: :patch}) do |f| %>
          <%= hidden_field_tag 'comment_id', comment.id  %>
          <div class="mb-2">
            <textarea name="body", required = true, class="dark:bg-zinc-700 dark:text-slate-300 dark:placeholder-white placeholder-gray-900 shadow border dark:border-gray-800 rounded-lg  w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline"><%=comment.body%></textarea>
          </div>
          <div class="flex float-right">
            <button role="submit" class="p-2 rounded-lg -md bg-blue-500 text-slate-200 hover:bg-blue-400" required>Save</button>
          </div>
        <% end %>
      </div>
      <div x-show="! open">
        <!-- Context -->
        <div class="p-1" style="line-height: 100%;display: flex;justify-content: left;flex-wrap: wrap;white-space: pre-wrap;">
          <%=render 'layouts/comment_body', {comment: comment}  %>
        </div>
      </div>
    </div>
    <div>
      <% unless current_user.nil?%>
        <div class="float-left mt-2" x-data="{ count: <%=comment.likes.size%>, liked: <%=!comment.likes.select{|item| item.user_id == current_user.id}.empty?%> }">
          <a href="javascript:add_like(<%=!current_user.nil? ? current_user.id : -1 %>,<%=comment.id%>, null)" @click="if (liked) {count -=1; liked = false;} else { count +=1; liked = true;}">
            <svg xmlns="http://www.w3.org/2000/svg" id="comment-heart-<%=comment.id%>" class="dark:text-slate-300 float-left <%='text-blue-500 dark:text-blue-500' if (!current_user.nil? && !comment.likes.select{|item| item.user_id == current_user.id}.empty?)%> float-left mr-1.5 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5" />
            </svg>
          </a>
          <button id="dropdownUsersButton" x-text = "count" data-dropdown-toggle="dropdownUsers-<%=comment.id%>" data-dropdown-placement="bottom" class="float-left ml-1 text-gray-500 dark:text-gray-400  font-light" type="button">
            <%="#{comment.likes.size}"%>
          </button>
          <!-- Dropdown menu -->
          <div id="dropdownUsers-<%=comment.id%>" class="hidden z-10 w-60 rounded-lg shadow bg-white dark:bg-zinc-800 block" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(286px, 70px);" data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom">
            <ul class="overflow-y-auto py-1 h-48 text-gray-700 dark:text-gray-200" aria-labelledby="dropdownUsersButton">
              <% unless comment.likes.size.zero? %>
                <% comment.likes.each do |like|%>
                  <li>
                    <a href="<%=user_public_profile_path(like.user.username)%>" class="flex items-center py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                      <% if like.user.avatar.attached? %>
                        <%= image_tag like.user.avatar.variant(:thumb), class: 'mr-2 w-6 h-6 rounded-full'%>
                      <% else %>
                        <%=image_tag("#{ENV['DEFAULT_AVATAR_IMAGE_PATH']}", :alt => "user photo", class: 'mr-2 w-6 h-6 rounded-full') %>
                      <% end %>
                      <%=like.user.full_name%>
                    </a>
                  </li>
                <% end %>
              <% else %>
                <li>
                  No likes
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="mt-4 w-full text-right" x-data="{ open_reply: false, word: 'Reply' }">
          <button class="" x-on:click="open_reply = ! open_reply, word = (word == 'Reply') ? 'Cancel' : 'Reply'" x-text="word">Reply</button>
          <div x-show="open_reply">
            <%= form_with(url: save_new_comment_path, html: { method: :put, class: "dark:bg-zinc-800 w-full bg-white rounded-lg pt-2"}) do |f| %>
              <%= hidden_field_tag 'parent_id', comment.id  %>
              <%= hidden_field_tag 'comment_id', comment.id  %>
              <div class="w-full md:w-full mb-2 mt-2">
                <textarea name="body", required = true, class="dark:bg-zinc-700 dark:text-slate-300 dark:placeholder-white placeholder-gray-900 shadow border dark:border-gray-800 rounded-lg  w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline"></textarea>
              </div>
              <div class="flex float-right">
                <button role="submit" class="p-2 rounded-lg -md bg-blue-500 text-slate-200 hover:bg-blue-400" required>Save</button>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <%= render comment.replies %>
  </div>
</div>