config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope "/:locale", locale: /en|ka|ua/ do
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")

    get "/@:username/posts", to: "posts#user_posts", as: :user_posts
    get "/@:username/friends", to: "friends#user_friends", as: :user_friends
    get "/@:username", to: "posts#user_posts", as: :user_public_profile
    get "/posts/new", to: "posts#new_post", as: :create_new_post
    get "/post/:id/edit", to: "posts#edit_post", as: :edit_post
    patch "/post/:id", to: "posts#save_edit_post", as: :save_edit_post
    get "/@:username/post/:id", to: "posts#post", as: :show_post
    put "/posts/save", to: "posts#save_new_post", as: :save_new_post
    get "/post/:id/toggle_status", to: "posts#toggle_post_status", as: :toggle_post_status
    get "/profile/posts", to: "posts#user_posts_list", as: :user_posts_list
    get "/profile/settings", to: "users#settings", as: :user_settings
    get "/profile/settings/avatar", to: "users#avatar", as: :avatar
    get "/profile/settings/appearance", to: "users#appearance", as: :appearance
    post "/profile/appearance", to: "users#save_appearance", as: :save_appearance
    post "/profile/avatar", to: "users#save_avatar", as: :save_user_avatar
    get "/profile/settings/addresses", to: "addresses#address", as: :address
    get "/profile/settings/addresses/new", to: "addresses#new_address", as: :new_address
    post "/profile/addresses/new", to: "addresses#new_address", as: :find_address
    put "/profile/addresses/new", to: "addresses#new", as: :save_address    
    put "/post/:id/add_comment", to: "comments#save", as: :save_new_comment
    patch "/post/:id/comments/:comment_id/update", to: "comments#update", as: :save_edit_comment
    get "/user/activity", to: "users#activity", as: :user_profile_activity
    delete "/posts/:id/delete", to: "posts#delete_user_post", as: :delete_user_post
    get "/profile/settings/phones/new", to: "phones#new", as: :new_phone
    put "/profile/phones/new", to: "phones#save_new_phone", as: :save_phone   
    get "/profile/settings/phones", to: "phones#index", as: :phone
    delete "/profile/phone/:phone/delete", to: "phones#delete", as: :delete_phone
    get "/dm", to: "messages#index", as: :direct_messages
    get "/dm/@:username", to: "messages#user", as: :user_direct_messages

    get "/profile/settings/privacy", to: "privacy#index", as: :privacy
    put "/profile/settings/privacy", to: "privacy#save", as: :save_privacy
    get "/categories/new", to: "categories#new", as: :new_category
    put "/categories/new", to: "categories#create", as: :save_new_category
    get "/profile/categories", to: "categories#index", as: :user_post_actegories
    get "/category/:name", to: "categories#category_posts", as: :show_category_posts
    match '/search',  to: 'posts#search_posts', via: 'get', as: :search
    get "/charges/new", to: 'charges#new', as: :new_charge
    get "/premium", to: "users#premium", as: :premium
    post "/charges/new", to: 'charges#create_subscription', as: :charges
    match '/auth/:provider/callback', :to => 'omniauth#google_oauth2', :via => [:get, :post]

    post '/user/accept', to: 'requests#accept', as: :accept_friend
  end
  
  get '*all', to: 'application#error_page', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  resources :webhooks, only: [:create]
  put '/request/create', to: 'requests#create', as: :sent_friend_request
  delete '/request/destroy', to: 'requests#destroy', as: :destroy_friend_request
  post "/likes/save", to: "likes#save", as: :save_like
  # get '*unmatched_route', to: 'application#error_page'

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])
      @user_obj = @user[:user]

      if @user[:new_user] == true
        force_password_change @user_obj
        return
      end

      if @user_obj.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user_obj, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user_obj.errors.full_messages.join("\n")
      end
  end

  def force_password_change(user_obj)
    flash[:notice] = "Please Set your password!"
    sign_in(:user, user_obj)
    token = user_obj.send(:set_reset_password_token)
    sign_out(user_obj)
    redirect_to(edit_password_path(:user, reset_password_token: token))
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def avatar;end

  def appearance;end

  def save_appearance
    current_user.settings(:settings).user_post_color = params[:settings][:user_post_color] unless params[:settings][:user_post_color].nil? 
    if current_user.save!
      flash[:notice] = 'Appearance settings updated Successfully!'
      redirect_to user_settings_path
    else
      render @user_avatar.errors, status: :unprocessable_entity
    end 
  end

  def save_avatar 
    @user_avatar = current_user.avatar.attach(params[:settings][:avatar]) unless params[:settings][:avatar].nil? 
    if current_user.save!
      flash[:notice] = 'Avatar updated Successfully!'
      redirect_to user_settings_path
    else
      flash.now[alert:] = "could not save avatar."
      render @user_avatar.errors, status: :unprocessable_entity
    end
  end

  def activity
    @registered = current_user
    @posts = @registered.posts
    @comments = @registered.comments
    @likes = @registered.likes
    @address = @registered.addresses.first
    @activity = (@posts + @comments + @likes).group_by{|x| x.created_at.strftime("%b %d, %Y")}.sort.reverse

    render 'users/index'
  end

  def premium
    flash[:notice] = "Payment success!" if params[:success] == 1
    @subscription = current_user.subscriptions.last
    @status = current_user.premium?
  end

  private

  def user_settings
    params.permit(:avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<% content_for(:html_title) { @user.full_name } %>
<div class="rounded-lg my-3 w-72 max-w-72 inline-block fixed">
  <div class="rounded-lg overflow-hidden shadow-xl my-3 bg-blue-500 dark:bg-zinc-800">
    <div class="flex justify-center mt-8">
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar.variant(:thumb), class: 'rounded-lg -full border-solid border-white border-2 -mt-3'%>
      <% else %>
        <%=image_tag("#{ENV['DEFAULT_AVATAR_IMAGE_PATH']}", :height => '100', :width => '100', :alt => "user photo", class: 'rounded-lg -full shadow-lg') %>
      <% end %>
    </div>
    <div class="text-center px-3 pb-6 pt-2">
      <% unless @user.id == current_user.id %>
        <% if @user.friend? current_user %>
          <button type="button" class="inline-flex item-center text-gray-900 bg-white focus:outline-none hover:bg-gray-100 rounded-lg py-2 px-3 mb-2 text-xs font-medium text-center dark:bg-blue-400 dark:hover:bg-blue-500  dark:text-white">
            <%=t(:unfriend)%>
          </button>
          <% if @user.follow? current_user %>
            <button type="button" class="inline-flex item-center text-gray-900 bg-white focus:outline-none hover:bg-gray-100 rounded-lg py-2 px-3 mb-2 text-xs font-medium text-center dark:bg-blue-400 dark:hover:bg-blue-500  dark:text-white">
              <%=t(:unfollow)%>
            </button>
          <% else %>
            <button type="button" class="inline-flex item-center text-gray-900 bg-white focus:outline-none hover:bg-gray-100 rounded-lg py-2 px-3 mb-2 text-xs font-medium text-center dark:bg-blue-400 dark:hover:bg-blue-500  dark:text-white">
              <%=t(:follow)%>
            </button>
          <% end %>
        <% elsif current_user.request_sent?(@user)%>
          <%=button_to t(:delete_request), destroy_friend_request_path, params: {'to_user_id' => @user.id}, method: :delete, class: "inline-flex item-center text-gray-900 bg-white focus:outline-none hover:bg-gray-100 rounded-lg py-2 px-3 mb-2 text-xs font-medium text-center dark:bg-blue-400 dark:hover:bg-blue-500  dark:text-white"%>
        <% else %>
          <%=button_to t(:add_friend), sent_friend_request_path, params: {'to_user_id' => @user.id}, method: :put, class: "inline-flex item-center text-gray-900 bg-white focus:outline-none hover:bg-gray-100 rounded-lg py-2 px-3 mb-2 text-xs font-medium text-center dark:bg-blue-400 dark:hover:bg-blue-500  dark:text-white"%>
        <% end %>
      <% end %>
      <h3 class="text-white text-sm bold font-sans"><%=@user.full_name%></h3>
      <p class="mt-2 font-sans font-light text-white">about me</p>
    </div>
    <div class="flex justify-center pb-3 text-white">
      <div class="text-center mr-3 border-r pr-3">
        <h2>34</h2>
        <span>Photos</span>
      </div>
      <div class="text-center">
        
        <span>
        <%=link_to user_friends_path(@user.username), class: "text-blue-400 hover:underline" do %>
        <h2><%=@user.friends.size%></h2>
        <%=t(:friends)%>
        <% end %>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% content_for(:html_title) { 'activity_logs' } %>
<%=render "layouts/users_sidebar" %>
<div class = "mt-10 float-left w-full max-w-4xl content-center">

  <ol class="relative border-l border-gray-200 dark:border-gray-700">
    <% @activity.each do |activity_type|%>
      <% activity_type.each do |activity_item|%>
        <% if activity_item.class.name == 'Array'%>
          <% activity_item.each do |item| %>
            <% if item.class.name == 'Post'%>
              <li class="mb-4 ml-6">
                <span class="flex absolute -left-3 justify-center items-center w-6 h-6 bg-blue-200 rounded-lg -full ring-8 ring-white dark:ring-gray-900 dark:bg-blue-900">
                  <% if item.user.avatar.attached? %>
                    <%= image_tag item.user.avatar.variant(:thumb), class: 'rounded-lg -full shadow-lg'%>
                  <% else %>
                    <%=image_tag("/images/users/profile_picture.jpg", :alt => "user photo", class: 'rounded-lg -full shadow-lg') %>
                  <% end %>
                </span>
                <div class = "dark:bg-zinc-800 bg-white rounded-lg  border border-gray-200 shadow-sm dark:bg-zinc-900 dark:border-gray-600">
                  <div class="justify-between items-center p-4 sm:flex">
                    <time class="mb-1 text-xs font-normal text-gray-400 sm:order-last sm:mb-0"><%= time_ago_in_words(item.created_at).to_s + " ago" %></time>
                    <div class="text-sm font-normal text-gray-500 lex dark:text-gray-300"><%=h(item.user.username)%> has created new post <a target = "_blank" href="<%=show_post_path(item.user.username, item.hashid)%>" class="font-semibold text-blue-600 dark:text-blue-500 hover:underline"><%="#{item.text[0,12]}..."%></a> </div>
                  </div>
                  <%=render 'posts/post', post: item  %>
                </div>
              </li>
            <% elsif item.class.name == 'Comment'%>
              <li class="mb-10 ml-6">
                <span class="flex absolute -left-3 justify-center items-center w-6 h-6 bg-blue-200 rounded-lg -full ring-8 ring-white dark:ring-gray-900 dark:bg-blue-900">
                  <% if item.user.avatar.attached? %>
                    <%= image_tag item.user.avatar.variant(:thumb), class: 'rounded-lg -full shadow-lg'%>
                  <% else %>
                    <%=image_tag("#{ENV['DEFAULT_AVATAR_IMAGE_PATH']}", :alt => "user photo", class: 'rounded-lg -full shadow-lg') %>
                  <% end %>
                </span>
                <div class="p-4 bg-white dark:bg-zinc-800 rounded-lg  border border-gray-200 shadow-sm dark:bg-zinc-900 dark:border-gray-600">
                  <div class="justify-between items-center mb-3 sm:flex">
                    <time class="mb-1 text-xs font-normal text-gray-400 sm:order-last sm:mb-0"><%= time_ago_in_words(item.created_at).to_s + " ago" %></time>
                    <div class="text-sm font-normal text-gray-500 lex dark:text-gray-300"><%=h(item.user.username)%> has commented on <a target = "_blank" href="<%=show_post_path(item.user.username, item.post.hashid)%>" class="font-semibold text-blue-600 dark:text-blue-500 hover:underline"><%=item.post.text[0,12]%></a></div>
                  </div>
                  <div class="p-3 text-sm font-normal text-gray-500 bg-gray-50 rounded-lg  border border-gray-200 dark:bg-zinc-700 dark:border-gray-500 dark:text-gray-300">
                    <%=render 'layouts/comment_body', {comment: item}  %>
                  </div>
                </div>
              </li>
            <% else %>
              <li class="mb-10 ml-6">
                <span class="flex absolute -left-3 justify-center items-center w-6 h-6 bg-blue-200 rounded-lg -full ring-8 ring-white dark:ring-gray-900 dark:bg-blue-900">
                  <% if item.user.avatar.attached? %>
                    <%= image_tag item.user.avatar.variant(:thumb), class: 'rounded-lg -full shadow-lg'%>
                  <% else %>
                    <%=image_tag("/images/users/profile_picture.jpg", :alt => "user photo", class: 'rounded-lg -full shadow-lg') %>
                  <% end %>
                </span>
                <div class="p-4 dark:bg-zinc-800 bg-white rounded-lg  dark:bg-zinc-800border border-gray-200 shadow-sm dark:bg-zinc-900 dark:border-gray-600">
                  <div class="justify-between items-center mb-3 sm:flex">
                    <time class="mb-1 text-xs font-normal text-gray-400 sm:order-last sm:mb-0"><%= time_ago_in_words(item.created_at).to_s + " ago" %></time>
                    <div class="text-sm font-normal text-gray-500 lex dark:text-gray-300">
                      <%=h(item.user.username)%> has 
                      👍🏼
                      <%=item.comment.nil? ? "post" : "comment" %> on <a target = "_blank" href="<%=item.comment.nil? ? show_post_url(item.post.user.username, item.post.hashid) : show_post_url(item.comment.post.user.username, item.comment.post.hashid) %>" class="font-semibold text-blue-600 dark:text-blue-500 hover:underline"><%=item.comment.nil? ? item.post.text[0,12] : item.comment.post.text[0,12] %></a></div>
                  </div>
                  <div class="p-3 text-sm font-normal text-gray-500 bg-gray-50 rounded-lg  border border-gray-200 dark:bg-zinc-700 dark:border-gray-500 dark:text-gray-300">
                    <%=item.comment.nil? ? item.post.text[0,12] : item.comment.body%>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>
        <% else %>
          <li class="text-xl mb-6 text-center bold dark:text-slate-300"><%=activity_item%></li>
        <% end %>
      <% end %>
    <% end %>
    <li class="text-xl mb-6 dark:text-slate-300 text-center bold"><%=@registered.created_at.strftime("%b %d, %Y")%> </li>
    <li class="mb-10 ml-6">
      <span class="flex absolute -left-3 justify-center items-center w-6 h-6 bg-blue-200 rounded-lg -full ring-8 ring-white dark:ring-gray-900 dark:bg-blue-900">
        <% if @registered.avatar.attached? %>
          <%= image_tag @registered.avatar.variant(:thumb), class: 'rounded-lg -full shadow-lg'%>
        <% else %>
          <%=image_tag("#{ENV['DEFAULT_AVATAR_IMAGE_PATH']}", :alt => "user photo", class: 'rounded-lg -full shadow-lg') %>
        <% end %>
      </span>
      <div class="justify-between items-center p-4 bg-white dark:bg-zinc-800 rounded-lg  border border-gray-200 shadow-sm sm:flex dark:bg-zinc-900 dark:border-gray-600">
        <time class="mb-1 text-xs font-normal text-gray-400 sm:order-last sm:mb-0"><%= time_ago_in_words(@registered.created_at).to_s + " ago" %></time>
        <div class="text-sm font-normal text-gray-500 lex dark:text-gray-300"><%=h(@registered.username)%> <%=t('registered')%>  </div>
      </div>
    </li>
  </ol>
</div>

app/views/users/premium.html.erb
<% content_for(:html_title) { 'Premium' } %>
<%=render "layouts/users_sidebar" %>
<div class = "mt-10 float-left w-full max-w-4xl content-center">
  <div class="max-w-md w-full rounded-lg ">
    <% if @subscription && @status %>
      <div class="p-4 flex flex-col items-center bg-white rounded-lg  border shadow-md md:flex-row md:max-w-xl dark:border-gray-700 dark:bg-zinc-800">
        <img class="object-cover w-full h-96 rounded-lg -t-lg md:h-auto md:w-48 md:rounded-lg -none md:rounded-lg -l-lg" src="<%=image_url("premiumbadge.png")%>" alt="">
        <div class="flex flex-col justify-between p-4 leading-normal">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-slate-300"><%=t(:your_premium_plan_is_active)%></h5>
          <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%=t('days_left')%>: <%=(@subscription.end_at.to_date - Date.current).to_i%></p>
        </div>
      </div>
    <% else %>
      <div id="toast-danger" class="flex mt-4 items-center p-4 mb-4 w-full text-gray-500 bg-white rounded-lg  shadow dark:text-gray-400 dark:bg-zinc-800" role="alert">
        <div class="inline-flex flex-shrink-0 justify-center items-center w-8 h-8 text-yellow-500 bg-yellow-100 rounded-lg  dark:bg-yellow-800 dark:text-yellow-200">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span class="sr-only">Error icon</span>
        </div>
        <div class="ml-3 text-sm font-normal"><%=t(:you_dont_have_premium)%>&nbsp;·&nbsp;<%=link_to t("buy_now"), charges_path, class: "text-blue-500" %></div>
      </div>
    <% end %>
  </div>
</div>