config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope "/:locale", locale: /en|ka|ua/ do
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")

    get "/@:username/posts", to: "posts#user_posts", as: :user_posts
    get "/@:username/friends", to: "friends#user_friends", as: :user_friends
    get "/@:username", to: "posts#user_posts", as: :user_public_profile
    get "/posts/new", to: "posts#new_post", as: :create_new_post
    get "/post/:id/edit", to: "posts#edit_post", as: :edit_post
    patch "/post/:id", to: "posts#save_edit_post", as: :save_edit_post
    get "/@:username/post/:id", to: "posts#post", as: :show_post
    put "/posts/save", to: "posts#save_new_post", as: :save_new_post
    get "/post/:id/toggle_status", to: "posts#toggle_post_status", as: :toggle_post_status
    get "/profile/posts", to: "posts#user_posts_list", as: :user_posts_list
    get "/profile/settings", to: "users#settings", as: :user_settings
    get "/profile/settings/avatar", to: "users#avatar", as: :avatar
    get "/profile/settings/appearance", to: "users#appearance", as: :appearance
    post "/profile/appearance", to: "users#save_appearance", as: :save_appearance
    post "/profile/avatar", to: "users#save_avatar", as: :save_user_avatar
    get "/profile/settings/addresses", to: "addresses#address", as: :address
    get "/profile/settings/addresses/new", to: "addresses#new_address", as: :new_address
    post "/profile/addresses/new", to: "addresses#new_address", as: :find_address
    put "/profile/addresses/new", to: "addresses#new", as: :save_address    
    put "/post/:id/add_comment", to: "comments#save", as: :save_new_comment
    patch "/post/:id/comments/:comment_id/update", to: "comments#update", as: :save_edit_comment
    get "/user/activity", to: "users#activity", as: :user_profile_activity
    delete "/posts/:id/delete", to: "posts#delete_user_post", as: :delete_user_post
    get "/profile/settings/phones/new", to: "phones#new", as: :new_phone
    put "/profile/phones/new", to: "phones#save_new_phone", as: :save_phone   
    get "/profile/settings/phones", to: "phones#index", as: :phone
    delete "/profile/phone/:phone/delete", to: "phones#delete", as: :delete_phone
    get "/dm", to: "messages#index", as: :direct_messages
    get "/dm/@:username", to: "messages#user", as: :user_direct_messages

    get "/profile/settings/privacy", to: "privacy#index", as: :privacy
    put "/profile/settings/privacy", to: "privacy#save", as: :save_privacy
    get "/categories/new", to: "categories#new", as: :new_category
    put "/categories/new", to: "categories#create", as: :save_new_category
    get "/profile/categories", to: "categories#index", as: :user_post_actegories
    get "/category/:name", to: "categories#category_posts", as: :show_category_posts
    match '/search',  to: 'posts#search_posts', via: 'get', as: :search
    get "/charges/new", to: 'charges#new', as: :new_charge
    get "/premium", to: "users#premium", as: :premium
    post "/charges/new", to: 'charges#create_subscription', as: :charges
    match '/auth/:provider/callback', :to => 'omniauth#google_oauth2', :via => [:get, :post]

    post '/user/accept', to: 'requests#accept', as: :accept_friend
  end
  
  get '*all', to: 'application#error_page', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  resources :webhooks, only: [:create]
  put '/request/create', to: 'requests#create', as: :sent_friend_request
  delete '/request/destroy', to: 'requests#destroy', as: :destroy_friend_request
  post "/likes/save", to: "likes#save", as: :save_like
  # get '*unmatched_route', to: 'application#error_page'

end

app/models/post.rb
class Post < ApplicationRecord
  resourcify
  belongs_to :user, counter_cache: true 
  has_many :comments
  has_many :likes
  belongs_to :notification, optional: true
  include Hashid::Rails

  scope :active, -> { where(active: true) }

  validates :text, presence: true,  length: { maximum: 65000 }
  validates :active, inclusion: { in: [ true, false ] }

  def self.search(search)
    if search.present?
      Post.where('lower(text) LIKE ?', "%#{search.downcase}%")#.or(Post.where('lower(text) LIKE ?', "%#{search.downcase}%"))
    end
  end 

  def active?
    !!self.active
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :user_posts, :post, :search_posts]
  @@post_sort = { 'tl' => 'comments.likes_count desc', 'tr' => 'comments.count_of_replies desc', 'lt' => 'comments.created_at desc', 'ot' => 'comments.created_at asc'}
  PER_PAGE = 9
  PER_PAGE_COMMENTS = 15

  def index
    @post = Post.new
    @posts = Post.where(active: true).order('created_at desc').includes(:comments => [:user, :likes]).page(params['page']).per(PER_PAGE)
    render 'posts/index', locals: {profile: false, posts: @posts}
  end

  def user_posts
    begin
      @user = User.find_by(username: params[:username])
      @post = Post.new
      @posts = Post.where(user_id: @user.id, active: true).order('created_at desc').includes(:comments, user: :subscriptions).page(params['page']).per(PER_PAGE)
      render 'posts/index', locals: {user: @user, profile: true}
    rescue
      error_page
    end
  end

  def search_posts 
    @post = Post.new
    @posts = Post.search(params[:query]).where(active: true).order('created_at desc').includes(:comments, :user).page(params['page']).per(PER_PAGE)
    render 'posts/index', locals: {profile: false}
  end

  def new_post 
    @post = Post.new
    render 'posts/new'
  end

  def save_new_post
    @post = current_user.posts.build(post_params)
    authorize @post
    @res = @post.save
    respond_to do |format|
      if @res
        format.html { redirect_to root_path, notice: "post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def post 
    begin
      sort = @@post_sort.key?(params[:sort]) ? @@post_sort[params[:sort]] : @@post_sort['lt']
      @post = Post.active.find_by_hashid(params[:id])
      error_page unless @post.user.username == params[:username]
      @comments = @post.comments.is_parent.page(params['page']).per(PER_PAGE_COMMENTS).order(sort)
      @comment = Comment.new
    rescue
      error_page
    end
  end

  def edit_post 
    begin
      @post = current_user.posts.find_by_hashid(params[:id])
      render 'posts/edit'
    rescue
      error_page
    end 
  end
  
  def save_edit_post
    @post = current_user.posts.find_by_hashid(params[:id])
    @post.text = params[:text]
    @res = @post.save

    respond_to do |format|
      if @post.save
        format.html { redirect_back_or_to show_post_path(@post.user.username, @post.hashid), notice: "post was succesfully Edited." }
        format.json { render :'posts/edit', status: :created, location: @post }
      else
        format.html { render :'posts/edit', status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_posts_list 
    @posts = current_user.posts.order('created_at desc').page(params['page']).per(PER_PAGE)
    render 'posts/posts_list'
  end

  def toggle_post_status 
    begin
      @post = current_user.posts.find_by_hashid(params[:id])
      @post.active = !@post.active
      @post.save
      flash[:notice] = 'Successfully updatet status!'
      redirect_to user_posts_list_path
    rescue
      error_page
    end 
  end

  def delete_user_post
    begin
      post = current_user.posts.find_by_hashid(params[:id])
      post.destroy
      flash[:notice] = 'Successfully deleted post!'
      redirect_to user_posts_list_path
    rescue
      error_page
    end 
  end
  

  private 

  def post_params
    params.permit(:text, :active)
  end

end

app/views/posts/_new_post_form.html.erb
  <%= form_with(url: save_new_post_path, html: { method: :put, class: "dark:text-slate-300 rounded-lg  pt-6 pb-8 mb-4" }) do |f| %>
    <% if @post.errors.full_messages.any? %>
      <div class="p-4 text-sm text-red-500 bg-red-100 rounded-lg  dark:bg-red-200 dark:text-red-800" role="alert">
        <% @post.errors.full_messages.each do |error_message| %>
          <%=error_message %><br>
        <% end %>
      </div>
    <% end %>
    <div class="mb-2">
      <textarea name="text" rows="4" class="dark:bg-zinc-700 dark:text-slate-300 dark:placeholder-slate-300 text-xl placeholder-gray-900 shadow border dark:border-gray-800 rounded-lg  w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" placeholder="Say Something..." ></textarea>
    </div>
    <div class="flex p-1 float-right">
      <%= f.select :active, [[t(:save_and_public), true], [t(:save_draft), false]], {}, { class: 'p-2 dark:bg-zinc-900 text-sm dark:text-slate-300'} %>
      <button role="submit" class="rounded-lg  p-3 bg-blue-500 text-slate-200 hover:bg-blue-400" required><%=t(:post)%></button>
    </div>
  <% end %>

app/views/posts/_post.html.erb
<div class="mt-3 px-5 py-4 bg-white dark:bg-zinc-800 shadow rounded-lg  w-full">
  <div class="flex mb-4">
    <% if post.user.avatar.attached? %>
      <%= image_tag post.user.avatar.variant(:thumb), class: 'w-12 h-12 rounded-lg -full'%>
    <% else %>
      <%=image_tag("#{ENV['DEFAULT_AVATAR_IMAGE_PATH']}", :alt => "user photo", class: 'w-12 h-12 rounded-lg -full') %>
    <% end %>
    <div class="ml-2 mt-0.5 w-full">
      <span class="font-bold text-gray-900 bg-white font-medium rounded-lg  text-sm px-5 py-2.5 text-center inline-flex items-center  dark:bg-zinc-800 dark:border-gray-700 dark:text-white mr-2 mb-2">
        <%=link_to h(post.user.full_name), user_posts_path(post.user.username), class: "text-blue-400 hover:underline" %>&nbsp;
        <% if post.user.premium? %>
          <svg data-tooltip-target="tooltip-light" data-tooltip-style="light" xmlns="http://www.w3.org/2000/svg" class="dark:text-orange-400 text-orange-300 h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
          </svg>
          <div id="tooltip-light" role="tooltip" class="inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium dark:text-slate-300 text-gray-900 bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-gray-500 shadow-sm opacity-0 tooltip">
            <%=t(:premium_user)%>
            <div class="tooltip-arrow" data-popper-arrow></div>
          </div>
        <% end %>
        <%=link_to show_post_path(post.user.username, post.hashid) do%>
          <%=render 'layouts/post_date_section', post: post%>
        <% end %>
      </span>
    </div>
  </div>
  <p class="text-gray-800 dark:text-gray-100 leading-snug md:leading-normal">
    <div x-data="{ open: false, word: 'Edit' }">
      <% if current_user.present?  && current_user.id == post.user_id %>
        <button class="dark:text-slate-300 float-right" x-on:click="open = ! open, word = (word == 'Edit') ? 'Cancel' : 'Edit'" x-text="word"><%=t(:edit)%></button>
      <% end %>
      <div x-show="open">
        <%= form_with(url: save_edit_post_path(post.hashid), html: { method: :patch}) do |f| %>
          <%= hidden_field 'id', post.hashid  %>
          <div class="mb-2">
            <textarea name="text", required = true, class="dark:bg-zinc-700 dark:text-slate-300 dark:placeholder-white placeholder-gray-900 shadow border dark:border-gray-800 rounded-lg  w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline"><%=post.text%></textarea>
          </div>
          <div class="flex float-right">
            <button role="submit" class="p-2 rounded-lg -md bg-blue-500 text-slate-200 hover:bg-blue-400" required><%=t(:save)%></button>
          </div>
          <br>
        <% end %>
      </div>
      <div x-show="! open">
        <%= render 'layouts/post_text', post: post %>
      </div>
    </div>
    <!-- component -->
  </p>
  <div class="flex items-center justify-between text-slate-500 mt-4">
    <div class="flex space-x-4 md:space-x-8">
      <%=link_to show_post_path(post.user.username, post.hashid) do%>
        <div class="flex cursor-pointer items-center transition hover:text-slate-600">
          <svg xmlns="http://www.w3.org/2000/svg" class="dark:text-slate-300 mr-1.5 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
          </svg>
          <span id = "post-count-<%=post.id%>" x-text = "count" class="dark:text-slate-300"><%=post.comments.size%></span>
        </div>
      <% end %>
      <% unless current_user.nil?%>
        <div class="flex cursor-pointer items-center transition hover:text-slate-600" x-data="{ count: <%=post.likes.size%>, liked: <%=!post.likes.select{|item| item.user_id == current_user.id}.empty?%> }">
          <a href="javascript:add_like(<%=!current_user.nil? ? current_user.id : -1 %>,null,<%=post.id%>)" @click="if (liked) {count -=1; liked = false;} else { count +=1; liked = true;}">
            <svg xmlns="http://www.w3.org/2000/svg" id="post-heart-<%=post.id%>" class="dark:text-slate-300 float-left <%='text-blue-500 dark:text-blue-500' if (!current_user.nil? && !post.likes.select{|item| item.user_id == current_user.id}.empty?)%> mr-1.5 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5" />
            </svg>
          </a>
          <button id="dropdownUsersButton" x-text = "count" data-dropdown-toggle="dropdownUsers-<%=post.id%>" data-dropdown-placement="bottom" class="font-mediumtext-sm dark:text-slate-300 text-slate-500" type="button">
            <%="#{post.likes.size}"%>
          </button>
          <!-- Dropdown menu -->
          <div id="dropdownUsers-<%=post.id%>" class="hidden z-10 w-60 rounded-lg shadow bg-white dark:bg-zinc-800 block" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(286px, 70px);" data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom">
            <ul class="overflow-y-auto py-1 h-48 text-gray-700 dark:text-gray-200" aria-labelledby="dropdownUsersButton">
              <% unless post.likes.size.zero? %>
                <% post.likes.each do |like|%>
                  <li>
                    <a href="<%=user_public_profile_path(like.user.username)%>" class="flex items-center py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                      <% if like.user.avatar.attached? %>
                        <%= image_tag like.user.avatar.variant(:thumb), class: 'mr-2 w-6 h-6 rounded-full'%>
                      <% else %>
                        <%=image_tag("#{ENV['DEFAULT_AVATAR_IMAGE_PATH']}", :alt => "user photo", class: 'mr-2 w-6 h-6 rounded-full') %>
                      <% end %>
                      <%=like.user.full_name%>
                    </a>
                  </li>
                <% end %>
              <% else %>
                <li>
                  No likes
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/post.html.erb
<% content_for(:html_title) { @post.text[0,12] } %>
<div class="container mx-auto flex flex-wrap py-6">
  <!-- Post Section -->
  <section class="w-full flex flex-col items-center px-3 mx-auto">
    <article class="flex flex-col shadow my-4" style="min-width:100%!important;">
      <!-- Article Image -->
      <div class="dark:bg-zinc-800 rounded-xl bg-white flex flex-col justify-start p-6">
        <div class="flex mb-4">
          <% if @post.user.avatar.attached? %>
            <%= image_tag @post.user.avatar.variant(:thumb), class: 'w-12 h-12 rounded-lg -full'%>
          <% else %>
            <%=image_tag("#{ENV['DEFAULT_AVATAR_IMAGE_PATH']}", :alt => "user photo", class: 'w-12 h-12 rounded-lg -full') %>
          <% end %>
          <div class="ml-2 mt-0.5">
            <span class="font-bold text-gray-900 bg-white font-medium rounded-lg  text-sm px-5 py-2.5 text-center inline-flex items-center  dark:bg-zinc-800 dark:border-gray-700 dark:text-white mr-2 mb-2">
              <%=link_to user_posts_path(@post.user.username), class: "text-blue-400 hover:underline" do%>
                <%=h(@post.user.full_name) %>&nbsp;
              <% end %>
              <% if @post.user.premium? %>
                <svg data-tooltip-target="tooltip-light" data-tooltip-style="light" xmlns="http://www.w3.org/2000/svg" class="dark:text-orange-400 text-orange-300 h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
                </svg>
                <div id="tooltip-light" role="tooltip" class="inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium dark:text-slate-300 text-gray-900 bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-gray-500 shadow-sm opacity-0 tooltip">
                  Premium User
                  <div class="tooltip-arrow" data-popper-arrow></div>
                </div>
              <% end %>
              <%=render 'layouts/post_date_section', post: @post%>
            </span>
          </div>
        </div>
        <div x-data="{ open: false, word: 'Edit' }">
          <% if current_user.present?  && current_user.id == @post.user_id %>
            <button class="dark:text-slate-300 float-right" x-on:click="open = ! open, word = (word == 'Edit') ? 'Cancel' : 'Edit'" x-text="word"><%=t(:edit)%></button>
          <% end %>
          <div x-show="open">
            <%= form_with(url: save_edit_post_path, html: { method: :patch}) do |f| %>
              <div class="mb-2">
                <textarea name="text", required = true, class="dark:bg-zinc-700 dark:text-slate-300 dark:placeholder-white text-xl placeholder-gray-900 shadow border dark:border-gray-800 rounded-lg  w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline"><%=@post.text%></textarea>
              </div>
              <div class="flex float-right">
                <button role="submit" class="p-2 rounded-lg -md bg-blue-500 text-slate-200 hover:bg-blue-400" required><%=t(:save)%></button>
              </div>
            <% end %>
          </div>
          <div x-show="! open">
            <%= render 'layouts/post_text', post: @post %>
          </div>
        </div>
        <!-- component -->
        <% unless current_user.nil?%>
          <div class="float-right mt-4" x-data="{ count: <%=@post.likes.size%>, liked: <%=!@post.likes.select{|item| item.user_id == current_user.id}.empty?%> }">
            <a href="javascript:add_like(<%=!current_user.nil? ? current_user.id : -1 %>,null,<%=@post.id%>)" @click="if (liked) {count -=1; liked = false;} else { count +=1; liked = true;}">
              <svg xmlns="http://www.w3.org/2000/svg" id="post-heart-<%=@post.id%>" class="dark:text-slate-300 float-left <%='text-blue-500 dark:text-blue-500' if (!current_user.nil? && !@post.likes.select{|item| item.user_id == current_user.id}.empty?)%> float-left mr-1.5 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5" />
              </svg>
            </a>
            <button id="dropdownUsersButton" x-text = "count" data-dropdown-toggle="dropdownUsers-<%=@post.id%>" data-dropdown-placement="bottom" class="font-mediumtext-sm dark:text-slate-300 text-slate-500" type="button">
              <%="#{@post.likes.size}"%>
            </button>
            <!-- Dropdown menu -->
            <div id="dropdownUsers-<%=@post.id%>" class="hidden z-10 w-60 rounded-lg shadow bg-white dark:bg-zinc-800 block" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(286px, 70px);" data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom">
              <ul class="overflow-y-auto py-1 h-48 text-gray-700 dark:text-gray-200" aria-labelledby="dropdownUsersButton">
                <% unless @post.likes.size.zero? %>
                  <% @post.likes.each do |like|%>
                    <li>
                      <a href="<%=user_public_profile_path(like.user.username)%>" class="flex items-center py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                        <% if like.user.avatar.attached? %>
                          <%= image_tag like.user.avatar.variant(:thumb), class: 'mr-2 w-6 h-6 rounded-full'%>
                        <% else %>
                          <%=image_tag("#{ENV['DEFAULT_AVATAR_IMAGE_PATH']}", :alt => "user photo", class: 'mr-2 w-6 h-6 rounded-full') %>
                        <% end %>
                        <%=like.user.full_name%>
                      </a>
                    </li>
                  <% end %>
                <% else %>
                  <li>
                    No likes
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </article>
    <div class="w-full flex mx-auto items-center justify-center shadow-lg mx-8 mb-4">
      <%= form_with(url: save_new_comment_path, html: { method: :put, class: "dark:bg-zinc-800 w-full bg-white rounded-lg  px-4 pt-2" }) do |f| %>
        <% if @comment.errors.full_messages.any? %>
          <div class="p-4 text-sm text-red-500 bg-red-100 rounded-lg  dark:bg-red-200 dark:text-red-800" role="alert">
            <% @comment.errors.full_messages.each do |error_message| %>
              <%=error_message %><br>
            <% end %>
          </div>
        <% end %>
        <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
        <div class="flex flex-wrap -mx-3 mb-6">
          <div class="w-full md:w-full px-3 mb-2 mt-2">
            <textarea class="dark:bg-zinc-700 dark:text-slate-300 dark:placeholder-white placeholder-gray-900 shadow border dark:border-gray-800 rounded-lg  w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" name="body" placeholder='Type Your Comment' required></textarea>
          </div>
          <div class="w-full md:w-full items-start md:w-full px-3 text-right">
            <div class="-mr-1">
              <input type='submit' class="rounded-lg  p-2 bg-blue-500 text-slate-200 hover:bg-blue-400" value='Post Comment'>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <!-- component -->
    <% unless @comments.empty? %>
      <button id="dropdownDefault" data-dropdown-toggle="dropdown1" class="dark:text-slate-300 font-medium rounded-lg text-sm px-4 py-2.5 inline-flex" type="button">
        <%=t(:sort_by)%>
        <svg class="ml-2 w-4 h-4" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
      </button>
      <!-- Dropdown menu -->
      <div id="dropdown1" class="hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-zinc-900">
        <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefault">
          <li>
            <%= link_to t(:top_likes), request.params.merge(sort: "tl"), class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
          </li>
          <li>
            <%= link_to t(:most_replies), request.params.merge(sort: "tr"), class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
          </li>
          <li>
            <%= link_to t(:newest), request.params.merge(sort: "lt"), class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
          </li>
          <li>
            <%= link_to t(:oldest), request.params.merge(sort: "ot"), class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
          </li>
        </ul>
      </div>
      <% @comments.each do |comment| %>
        <%= render 'comments/comment', comment: comment %>
      <% end%>
      <div class="mx-auto text-center mt-10">
        <%= paginate @comments %>
      </div>
    <% end %>
  </section>
</div>