config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope "/:locale", locale: /en|ka|ua/ do
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")

    get "/@:username/posts", to: "posts#user_posts", as: :user_posts
    get "/@:username/friends", to: "friends#user_friends", as: :user_friends
    get "/@:username", to: "posts#user_posts", as: :user_public_profile
    get "/posts/new", to: "posts#new_post", as: :create_new_post
    get "/post/:id/edit", to: "posts#edit_post", as: :edit_post
    patch "/post/:id", to: "posts#save_edit_post", as: :save_edit_post
    get "/@:username/post/:id", to: "posts#post", as: :show_post
    put "/posts/save", to: "posts#save_new_post", as: :save_new_post
    get "/post/:id/toggle_status", to: "posts#toggle_post_status", as: :toggle_post_status
    get "/profile/posts", to: "posts#user_posts_list", as: :user_posts_list
    get "/profile/settings", to: "users#settings", as: :user_settings
    get "/profile/settings/avatar", to: "users#avatar", as: :avatar
    get "/profile/settings/appearance", to: "users#appearance", as: :appearance
    post "/profile/appearance", to: "users#save_appearance", as: :save_appearance
    post "/profile/avatar", to: "users#save_avatar", as: :save_user_avatar
    get "/profile/settings/addresses", to: "addresses#address", as: :address
    get "/profile/settings/addresses/new", to: "addresses#new_address", as: :new_address
    post "/profile/addresses/new", to: "addresses#new_address", as: :find_address
    put "/profile/addresses/new", to: "addresses#new", as: :save_address    
    put "/post/:id/add_comment", to: "comments#save", as: :save_new_comment
    patch "/post/:id/comments/:comment_id/update", to: "comments#update", as: :save_edit_comment
    get "/user/activity", to: "users#activity", as: :user_profile_activity
    delete "/posts/:id/delete", to: "posts#delete_user_post", as: :delete_user_post
    get "/profile/settings/phones/new", to: "phones#new", as: :new_phone
    put "/profile/phones/new", to: "phones#save_new_phone", as: :save_phone   
    get "/profile/settings/phones", to: "phones#index", as: :phone
    delete "/profile/phone/:phone/delete", to: "phones#delete", as: :delete_phone
    get "/dm", to: "messages#index", as: :direct_messages
    get "/dm/@:username", to: "messages#user", as: :user_direct_messages

    get "/profile/settings/privacy", to: "privacy#index", as: :privacy
    put "/profile/settings/privacy", to: "privacy#save", as: :save_privacy
    get "/categories/new", to: "categories#new", as: :new_category
    put "/categories/new", to: "categories#create", as: :save_new_category
    get "/profile/categories", to: "categories#index", as: :user_post_actegories
    get "/category/:name", to: "categories#category_posts", as: :show_category_posts
    match '/search',  to: 'posts#search_posts', via: 'get', as: :search
    get "/charges/new", to: 'charges#new', as: :new_charge
    get "/premium", to: "users#premium", as: :premium
    post "/charges/new", to: 'charges#create_subscription', as: :charges
    match '/auth/:provider/callback', :to => 'omniauth#google_oauth2', :via => [:get, :post]

    post '/user/accept', to: 'requests#accept', as: :accept_friend
  end
  
  get '*all', to: 'application#error_page', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  resources :webhooks, only: [:create]
  put '/request/create', to: 'requests#create', as: :sent_friend_request
  delete '/request/destroy', to: 'requests#destroy', as: :destroy_friend_request
  post "/likes/save", to: "likes#save", as: :save_like
  # get '*unmatched_route', to: 'application#error_page'

end

app/views/layouts/_comment_body.html.erb
<%=simple_format(h(comment.body).gsub(/(#)\S+/, '<a href="/{loc}/hashtag/\0" class = "text-blue-800" >\0</a>').gsub(/(@)\S+/, '<a class = "text-blue-800" href="/{loc}/\0/posts">\0</a>').gsub('{loc}', I18n.locale.to_s).html_safe, { class: "leading-normal text-gray-900 dark:text-slate-300 border-l-2 px-1 border-blue-500 rounded-lg break-all"}) %>

app/views/layouts/_navbar.html.erb
<script>
  (function() {
    dropdown.hide();
  })();
</script>
<nav class="w-full py-4 bg-blue-500 dark:bg-zinc-800 shadow user-color-bg sticky top-0 z-50">
  <div class="w-8/12 container mx-auto flex flex-wrap items-center justify-between">
    <nav>
      <ul class="flex items-center justify-between font-bold text-sm text-slate-200 no-underline">
        <li><%= link_to root_path, class: 'hover:text-gray-200 hover:underline' do %>
            <%=image_tag(image_url("logo.png"), width: "50", height: "auto")%>
          <% end %>
        </li>
        <li>
          <button
  id="theme-toggle"
  type="button"
  class="text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5"
>
            <svg
    id="theme-toggle-dark-icon"
    class="w-5 h-5 hidden"
    fill="currentColor"
    viewBox="0 0 20 20"
    xmlns="http://www.w3.org/2000/svg"
  >
              <path
      d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"
    ></path>
            </svg>
            <svg
    id="theme-toggle-light-icon"
    class="w-5 h-5 hidden"
    fill="currentColor"
    viewBox="0 0 20 20"
    xmlns="http://www.w3.org/2000/svg"
  >
              <path
      d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z"
      fill-rule="evenodd"
      clip-rule="evenodd"
    ></path>
            </svg>
          </button>
        </li>
      </ul>
    </nav>
    <%=render "layouts/search_form" %>
    <div class="flex items-center text-lg no-underline text-slate-200 pr-6">
      <% unless signed_in? %>
        <ul class="flex items-center justify-between font-bold text-sm text-slate-200 no-underline">
          <li><%= link_to t('sign_in'), new_user_session_path, class: 'hover:text-gray-200 hover:underline px-4' %></li>
          <li><%= link_to t('sign_up'), new_user_registration_path, class: 'hover:text-gray-200 hover:underline px-4' %></li>
        </ul>
      <% end %>
      <% if signed_in? %>
        <span class="relative inline-block ml-2">
          <a href = "<%=direct_messages_path%>">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z" />
            </svg>
            <% if false %>
              <span class="absolute top-0 left-4 px-2 py-1 text-xs font-bold leading-none text-red-100 transform bg-red-600 rounded-lg -full">0</span>
            <% end %>
          </a>
        </span>
        <span class="relative inline-block ml-2 mr-4 mt-2">
          <button id="dropdownDefault" data-dropdown-toggle="notifications-dropdown" class="text-whitetext-center items-center" type="button">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
            </svg>
            <% unless current_user.notifications.all_except(current_user).size.zero? %>
              <span class="absolute top-0 left-4 px-2 py-1 text-xs font-bold leading-none text-red-100 transform bg-red-600 rounded-lg -full"><%=current_user.notifications.all_except(current_user).size%></span>
            <% end %>
          </button>
          <!-- Dropdown menu -->
          <div id="notifications-dropdown" class="hidden z-10 w-96 bg-white rounded divide-y divide-gray-100 shadow dark:bg-zinc-900 block" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(319px, 70px);" data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom">
            <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefault">
              <% unless current_user.notifications.all_except(current_user).size.zero? %>
                <% current_user.notifications.all_except(current_user).each do |notification| %>
                  <%= render "notifications/#{notification.ntype.downcase}_#{notification.naction.downcase}_#{notification.non.downcase}", notification: notification %>
                <% end %>
                <li class="w-full text-center p-4">
                <%=link_to t(:view_all_notifications), "#", class:"underline font-bold"%>
                </li>
              <% else %>
                <li>No notifications</li>
              <% end %>
            </ul>
          </div>
          <a href = "#">
          </a>
        </span>
        <button type="button" class="flex mr-3 text-sm rounded-lg -full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="dropdown">
          <span class="sr-only">Open user menu</span>
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar.variant(:thumb), class: 'w-8 h-8 rounded-lg -full'%>
          <% else %>
            <%=image_tag("#{ENV['DEFAULT_AVATAR_IMAGE_PATH']}", :alt => "user photo", class: 'w-8 h-8 rounded-lg -full') %>
          <% end %>
        </button>
        <div class="z-50 my-4 text-base list-none bg-white rounded-lg divide-y divide-gray-100 shadow dark:bg-zinc-900 dark:divide-gray-600 hidden" id="dropdown" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(1560px, 54px);" data-popper-placement="bottom">
          <div class="py-3 px-4">
            <span class="block text-sm text-gray-900 dark:text-slate-300"><%=h(current_user.full_name)%></span>
            <span class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400"><%=h(current_user.email)%></span>
          </div>
          <ul class="py-1" aria-labelledby="dropdown">
            <li><%= link_to premium_path, class: 'block bg-orange-300 dark:bg-orange-400 dark:hover:bg-orange-500 hover:bg-orange-400 py-2 px-4 text-sm text-gray-700 dark:text-gray-200 dark:hover:text-slate-200' do %>
                <span class="float-left><%=t("premium")%></span>
                <svg xmlns="http://www.w3.org/2000/svg" class="pr-2 float-left h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
                </svg>
              <% end %>
            </li>
            <li><%= link_to t("dashboard"), edit_user_registration_path, class: 'block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-slate-200' %></li>
            <li><%= link_to t("Activity logs"), user_profile_activity_path, class: 'block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-slate-200' %></li>
            <li><%= link_to t("log_out"), destroy_user_session_path,  class: 'block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-slate-200'%></li>
          </ul>
        </div>
        <button data-collapse-toggle="mobile-menu-2" type="button" class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg  md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mobile-menu-2" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
          </svg>
          <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
          </svg>
        </button>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_post_text.html.erb
<div class="dark:text-slate-300 text-gray-800"><%=simple_format(h(post.text).gsub(/(#)\S+/, '<a href="/{loc}/hashtag/\0" class = "text-blue-800" >\0</a>').gsub(/(@)\S+/, '<a class = "text-blue-800" href="/{loc}/\0/posts">\0</a>').gsub('{loc}', I18n.locale.to_s).gsub(URI.regexp, '<a class = "text-blue-800" target = "_blank" href="\0">\0</a>')).html_safe %></div>

app/views/layouts/_search_form.html.erb
<%=form_with(url: search_path, method: :get, class: "mx-auto w-1/2	") do%>
  <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-gray-300"><%=t('search')%></label>
  <div class="relative">
    <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
      <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
    </div>
    <input name = "query" type="search" id="default-search" class="block p-4 pl-10 w-full text-sm text-gray-900 bg-white rounded-lg  border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-zinc-700 dark:border-gray-600 dark:placeholder-slate-200 dark:text-slate-300 dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="<%=t('search_rocket')%>" required>
    <button type="submit" class="text-slate-200 absolute right-2.5 bottom-2.5 bg-blue-500 hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-100 font-medium rounded-lg  text-sm px-4 py-2 dark:bg-blue-400 dark:hover:bg-blue-500 dark:focus:ring-blue-600"><%=t('search')%></button>
  </div>
<% end %>

app/views/layouts/_settings_nav.html.erb
<div class="grid col-auto gap-4 pt-10 lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1">
  <%= link_to avatar_path do %>
    <div class="p-4 bg-indigo-500 text-slate-200 text-center rounded-lg "><%=t("profile_picture")%></div>
  <% end %>
  <%= link_to appearance_path do %>
    <div class="p-4 bg-indigo-500 text-slate-200 text-center rounded-lg "><%=t("post_appearance_settings")%></div>
  <% end %>
  <div class="inline-flex w-full" role="group">
    <%= link_to address_path, class: "inline-flex p-4 bg-indigo-500 text-slate-200 text-center rounded-l-lg" do %>
      <%=t("addresses")%>
    <% end %>
    <%= link_to new_address_path, class: "inline-flex p-4 bg-indigo-600 text-slate-200 text-center rounded-r-lg" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v2H7a1 1 0 100 2h2v2a1 1 0 102 0v-2h2a1 1 0 100-2h-2V7z" clip-rule="evenodd" />
      </svg>
    <% end %>
  </div>
  <div class="inline-flex w-full" role="group">
    <%= link_to phone_path, class: "inline-flex p-4 bg-indigo-500 text-slate-200 text-center rounded-l-lg" do %>
      <%=t("phones")%>
    <% end %>
    <%= link_to new_phone_path, class: "inline-flex p-4 bg-indigo-600 text-slate-200 text-center rounded-r-lg" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v2H7a1 1 0 100 2h2v2a1 1 0 102 0v-2h2a1 1 0 100-2h-2V7z" clip-rule="evenodd" />
      </svg>
    <% end %>
  </div>
</div>
<br>

app/views/layouts/_users_sidebar.html.erb
<style>
  .selected-menu-item
  {
     border-bottom:2px solid #3b82f680
  }
</style>
<aside class="sm:w-fullw-80 float-left mt-10 mr-10" aria-label="Sidebar">
  <div class="py-4 px-3 bg-gray-50 rounded-lg dark:bg-zinc-800">
    <ul class="space-y-2">
      <li class = "<%='selected-menu-item' if request.path == edit_user_registration_path%>">
        <a href="<%=edit_user_registration_path%>" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg  dark:text-slate-300 hover:bg-gray-100 dark:hover:bg-gray-700">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span class="ml-3"><%=t('edit_profile')%></span>
        </a>
      </li>
      <% if current_user.admin? %>
      <li class = "<%='selected-menu-item' if request.path == user_posts_list_path %>">
        <a href="<%=user_posts_list_path%>" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg  dark:text-slate-300 hover:bg-gray-100 dark:hover:bg-gray-700">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 10h16M4 14h16M4 18h16" />
          </svg>               <span class="flex-1 ml-3 whitespace-nowrap"><%=t('my_posts')%></span>
          <span class="inline-flex justify-center items-center p-3 ml-3 w-3 h-3 text-sm font-medium text-blue-600 bg-blue-200 rounded-lg -full dark:bg-blue-900 dark:text-blue-200"><%=current_user.posts.size%></span>
        </a>
      </li>
      <li class = "<%='selected-menu-item' if request.path == user_post_actegories_path %>">
        <a href="<%=user_post_actegories_path%>" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg  dark:text-slate-300 hover:bg-gray-100 dark:hover:bg-gray-700">
          <svg class="flex-shrink-0 w-6 h-6 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-slate-200" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"></path></svg>
          <span class="flex-1 ml-3 whitespace-nowrap"><%=t('post_categories')%></span>
          <span class="inline-flex justify-center items-center p-3 ml-3 w-3 h-3 text-sm font-medium text-blue-600 bg-blue-200 rounded-lg -full dark:bg-blue-900 dark:text-blue-200"><%=Category.all.size%></span>
        </a>
      </li>
      <% end %>
      <li class = "<%='selected-menu-item' if request.path == user_profile_activity_path%>">
        <a href="<%=user_profile_activity_path%>" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg  dark:text-slate-300 hover:bg-gray-100 dark:hover:bg-gray-700">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <span class="flex-1 ml-3 whitespace-nowrap"><%=t('Activity logs')%></span>
        </a>
      </li>
      <li class = "<%='selected-menu-item' if request.path == user_settings_path%>">
        <a href="<%=user_settings_path%>" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg  dark:text-slate-300 hover:bg-gray-100 dark:hover:bg-gray-700">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
          </svg>               <span class="flex-1 ml-3 whitespace-nowrap"><%=t('settings')%></span>
        </a>
      </li>
      <li class = "<%='selected-menu-item' if request.path == privacy_path%>">
        <a href="<%=privacy_path%>" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg  dark:text-slate-300 hover:bg-gray-100 dark:hover:bg-gray-700">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M20.618 5.984A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016zM12 9v2m0 4h.01" />
          </svg>               <span class="flex-1 ml-3 whitespace-nowrap"><%=t('privacy')%></span>
        </a>
      </li>
    </ul>
  </div>
</aside>